version: '3'

services:

  reverse-proxy:
    build:
      context: ./ingress/
      dockerfile: Dockerfile
    ports:
     - '${PORT:-8000}:80'
    depends_on:
     - frontend
     - backend

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_NAME=fraude

  mongo:
    image: mongo
